BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CategoryController : Controller
    {
        //Dependency injection
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            /*List<Category> objCategoryList = _unitOfWork.Categories.ToList();*/
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "The DisplayOrder cannot exactly match the Name");
            }
            if (ModelState.IsValid)
            {

                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Category created successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }


        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Id Null Error";
                //return View("Error");
                return NotFound();
            }
            //var categoryFromDb = _unitOfWork.Categories.Find(id);
            var categoryFromDb = _unitOfWork.Category.GetFirstOrDefault(x => x.Id == id);
            //var categoryFromDb = _unitOfWork.Categories.SingleOrDefault(x => x.Id == id);

            if (categoryFromDb == null)
            {
                TempData["Error"] = "This Category is not found";
                //return View("Error");
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "The DisplayOrder cannot exactly match the Name");
            }
            if (ModelState.IsValid)
            {
                //_unitOfWork.Add(obj);
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Category updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Id Null Error";
                return View("Error");
            }
            //var categoryFromDb = _unitOfWork.Categories.Find(id);
            var categoryFromDb = _unitOfWork.Category.GetFirstOrDefault(x => x.Id == id);
            if (categoryFromDb == null)
            {
                TempData["Error"] = "This Category is not found";
                //return View("Error");
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category obj)
        {
            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["Success"] = "Category deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }

}

BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
      
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Company company = new();
           
            if (id == null || id==0)
            {
                return View(company);
                //create company
            }
            else{

                company = _unitOfWork.Company.GetFirstOrDefault(x=>x.Id==id);
                return View(company);
                //update company
            }

        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
           
            if (ModelState.IsValid)
            {
                string operation = String.Empty;
                if (obj.Id == 0)
                {
                    _unitOfWork.Company.Add(obj);
                    operation = "created";
                }
                else
                {
                    _unitOfWork.Company.Update(obj);
                    operation = "updated";
                }

                _unitOfWork.Save();
                TempData["Success"] = "Company "+operation+ " successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }

        #region API CALLS
        //He we will be calling our API calls first
        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _unitOfWork.Company.GetAll();

            return Json(new { data = companyList });
        }
        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            
            var obj = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
           
            _unitOfWork.Company.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted Successfully" });
        }
        #endregion
    }
}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        //To access wwwroot, we need that web hosting environment, so we would have to get
        //that using dependency injection
        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {

            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(
                     x => new SelectListItem
                     {
                         Text = x.Name,
                         Value = x.Id.ToString()
                     }
                  ),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(
                     x => new SelectListItem
                     {
                         Text = x.Name,
                         Value = x.Id.ToString()
                     }
                  ),
            };
              
            if (id == null || id==0)
            {
                return View(productVM);
                //create product
            }
            else{
                
                productVM.Product=_unitOfWork.Product.GetFirstOrDefault(x=>x.Id==id);
                return View(productVM);
                //update product
            }

        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
           
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    //Generate a new file name
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName); //Rename the file,but I want to keep the same extension

                    if (obj.Product.ImageUrl != null) //Delete image when it exits
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
              
                    //And finally, I need to copy the file that was uploaded inside the product folder
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        //I want to copy that file to the location that we have inside the fileStreams
                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageUrl = @"\images\products\" + fileName + extension;
                }
                string operation = String.Empty;
                if (obj.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.Product);
                    operation = "created";
                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                    operation = "updated";
                }

                _unitOfWork.Save();
                TempData["Success"] = "Product "+operation+ " successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }

        #region API CALLS
        //He we will be calling our API calls first
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties:"Category,CoverType");

            return Json(new { data = productList });
        }
        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;

            var obj = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath)){
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.Product.Remove(obj);
            _unitOfWork.Save();
            //TempData["Success"] = "Cover Type deleted successfully";
            return Json(new { success = true, message = "Deleted Successfully" });
        }
        #endregion
    }
}

BulkyBookWeb/ViewComponent/ShoppingCartViewComponent.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BulkyBookWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
@using BulkyBookWeb.Languages
@using Microsoft.AspNetCore.Http
@using BulkyBook.Utility
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Localization
@inject IHttpContextAccessor HttpContextAccessor

@inject IHtmlLocalizer<Lang> _viewLocalizer;

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BulkyBookWeb</title>
	<link rel="stylesheet" href="~/css/bootswatchTheme.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />

	@*For _Notification*@
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

	@*For Icon from bootstrap 5*@
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
	@*Data table*@
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand text-light" href="#">KANTE</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarColor02">
					<ul class="navbar-nav me-auto">
						<li class="nav-item">
							<a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">@_viewLocalizer["page.Home"]</a>
						</li>
						@if (User.IsInRole(SD.Role_Admin))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">@_viewLocalizer["page.ContentM"]</a>
								<div class="dropdown-menu">
									<a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">@_viewLocalizer["page.Category"]</a>
									<a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">@_viewLocalizer["page.CoverType"]</a>
									<a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">@_viewLocalizer["page.Product"]</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">@_viewLocalizer["page.Company"]</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">@_viewLocalizer["page.CreateUser"]</a>
								</div>
							</li>
						}
						<li class="nav-item">
							<a class=nav-link asp-area="Admin" asp-controller="Order" asp-action="Index">
								@_viewLocalizer["page.Manage"]
							</a>
						</li>
						
						<li class="nav-item">
							<a class=nav-link asp-area="Customer" asp-controller="Cart" asp-action="Index">
								@await Component.InvokeAsync("ShoppingCart")
							</a>
						</li>
					

					</ul>
					<partial name="_LoginPartial" />
					
				</div>
			</div>
		</nav>

	</header>
	<div class="container">
		<main role="main" class="pb-3">
			<partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

	<footer class="footer text-muted bg-primary">
		<div class="container">
			&copy; 2022 - BulkyBookWeb
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<!--Sweetalerts-->
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<!--Data table js-->
	<script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
	<!--Toastr for _Notification-->
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<!--Tinymce-->
	<script src="https://cdn.tiny.cloud/1/b4dps06pofft5va7rh2a4eofyoinmbbdoh7qrebc1707da8o/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["Error"]');
    </script>

}